# Generated by Django 3.1.2 on 2020-10-21 19:55

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_class', models.CharField(choices=[('الصف الاول', 'الصف الاول'), ('الصف الثانى', 'الصف الثانى'), ('الصف الثالث', 'الصف الثالث'), ('الصف الرابع', 'الصف الرابع'), ('الصف الخامس', 'الصف الخامس'), ('الصف السادس', 'الصف السادس')], max_length=50)),
                ('question', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload)),
                ('p_class', models.CharField(choices=[('الصف الاول', 'الصف الاول'), ('الصف الثانى', 'الصف الثانى'), ('الصف الثالث', 'الصف الثالث'), ('الصف الرابع', 'الصف الرابع'), ('الصف الخامس', 'الصف الخامس'), ('الصف السادس', 'الصف السادس')], max_length=50)),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ans', models.CharField(max_length=100)),
                ('student_ans', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_ans', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
