# Generated by Django 3.1.2 on 2020-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
